project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"
include-in-header:
  - text: |
      <meta name="google-site-verification" content="j_gTCzWnr1jevnfvO9Y_sxECPpvnmmr3i7nuJjhDkiw" />
website:
  title: "Neu4mes"
  description: "Research Group focused on Phisically Informed Neural Networks for Mechanical and Mechatronic Systems"
  favicon: /assets/images/logomodely.png
  margin-header: |
    ![](/assets/images/logomodely.png)
  # image: /assets/images/<file>.png
  # site-url: https://<owner>.github.io/<repository>
  # repo-url: https://github.com/<owner>/<repository>
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    left: |
      Powered by [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) .
    center: |
      &copy; []{#current-year} created by Mattia PIAZZA.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications/index.qmd
        text: Publications
      - href: people/index.qmd
        text: People
      - href: neu4mes.qmd
        text: Neu4mes
      - href: contacts.qmd
        text: Contacts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




