---
title: "A Road Friction-Aware Anti-Lock Braking System Based on Model-Structured Neural Networks"
author: ["Mattia Piccinini", "Matteo Zumerle", "Johannes Betz", "Gastone Pietro Rosati Papini"]
publication: "IEEE Open Journal of Intelligent Transportation Systems, volume 6, 522-536 (2025)"
type: journal
categories: 
  - "Publications"
  - "Journal Articles"
  - "Model-Structured Neural Networks"
  - "Road Friction Estimation"
  - "Anti-Lock Braking Systems"
  - "Intelligent Transportation Systems"
url_source: 
url_preprint: 
journ: "IEEE Open Journal of Intelligent Transportation Systems"
issue: Volume 6
page: pp. 522-536
doi: "10.1109/OJITS.2025.3563347"
year: 2025
video: xQ_T96IjGP8
# image: ""
bibtex: bibtex.txt
---


<!-- ## Video

{{< video https://www.youtube.com/watch?v=xQ_T96IjGP8 >}} -->

## Abstract

The anti-lock braking system (ABS) is a vital safety feature in modern vehicles, preventing wheel lock during emergency braking. However, the performance of conventional ABS is often limited by the lack of real-time road friction information. This paper introduces a novel road friction-aware ABS, leveraging model-structured neural networks (MS-NNs) to learn the vehicle longitudinal dynamics in different road conditions. Our framework uses a robust criterion to dynamically select from a set of pre-trained MS-NNs based on the available sensor data, enabling real-time road friction estimation and autonomous adaptation of the ABS parameters. Simulation experiments demonstrate that the proposed MS-NN-based ABS significantly improves safety and performance across varying road conditions: the braking distances are reduced by 3.0%-40.4% compared to a conventional ABS, tuned for a specific road condition. Furthermore, the MS-NN’s architecture shows better accuracy, generalization and sample-efficiency compared to other neural networks in the literature, and is suitable for real-time deployment on automotive-grade hardware. Our implementation is open source and available in a public repository.

